version: "3.7"

services:
  infra:
    build:
      dockerfile: docker/Dockerfile
      context: .
    working_dir: /code
    user: root
    entrypoint: ""
    volumes:
      - $HOME:/root/:ro
      - $HOME/.aws/cli/cache:/root/.aws/cli/cache
      - $HOME/.cache/terraform-providers:/.tfcache
      - ./:/code
    environment:
      - TF_PLUGIN_CACHE_DIR=/.tfcache
      - TF_VAR_project_name=$PROJECT_NAME
      - TF_VAR_cloudflare_api_token=$CLOUDFLARE_API_TOKEN
      - TF_LOG
      - AWS_PROFILE
      - AWS_STS_REGIONAL_ENDPOINTS=regional
      - AWS_SDK_LOAD_CONFIG=1
